server:
  port: ${GATEWAY_PORT:8080}
  address: ${GATEWAY_HOST:127.0.0.1}
spring:
  application:
    name: peakrush-gateway
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:16379}
      timeout: 1s
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 15s
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
peakrush:
  backend-uri: ${BACKEND_URI:http://127.0.0.1:8081}
  limits:
    enabled: ${RATE_LIMIT_ENABLED:true}
    global-per-second: ${RATE_GLOBAL:1500}
    ip-per-second: ${RATE_IP:1200}
    token-per-second: ${RATE_TOKEN:20}

