CREATE TABLE IF NOT EXISTS app_user (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(64) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'USER',
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS product (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(160) NOT NULL,description TEXT NOT NULL,
 image_url VARCHAR(500) NOT NULL,original_price DECIMAL(12,2) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,
 category VARCHAR(32) NOT NULL DEFAULT '其他好物'
);
CREATE TABLE IF NOT EXISTS activity (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(160) NOT NULL,description TEXT NOT NULL,
 start_time DATETIME(3) NOT NULL,end_time DATETIME(3) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
 architecture_version INT NOT NULL,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS seckill_item (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,activity_id BIGINT NOT NULL,product_id BIGINT NOT NULL,
 seckill_price DECIMAL(12,2) NOT NULL,total_stock INT NOT NULL,available_stock INT NOT NULL,
 limit_per_user INT NOT NULL,generation VARCHAR(36) NOT NULL,version BIGINT NOT NULL DEFAULT 0,
 UNIQUE KEY uk_activity_product(activity_id,product_id),
 FOREIGN KEY(activity_id) REFERENCES activity(id),FOREIGN KEY(product_id) REFERENCES product(id)
);
CREATE TABLE IF NOT EXISTS seckill_request (
 request_id VARCHAR(110) PRIMARY KEY,user_id BIGINT NOT NULL,activity_id BIGINT NOT NULL,item_id BIGINT NOT NULL,
 quantity INT NOT NULL,payload_hash VARCHAR(64) NOT NULL,generation VARCHAR(36) NOT NULL,
 redis_reserved BOOLEAN NOT NULL,status VARCHAR(20) NOT NULL,reason VARCHAR(160),order_id BIGINT,
 state_version BIGINT NOT NULL DEFAULT 1,accepted_at DATETIME(3) NOT NULL,
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 KEY idx_request_item(item_id,status)
);
CREATE TABLE IF NOT EXISTS seckill_order (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,request_id VARCHAR(110) NOT NULL UNIQUE,user_id BIGINT NOT NULL,
 activity_id BIGINT NOT NULL,item_id BIGINT NOT NULL,quantity INT NOT NULL,
 unit_price DECIMAL(12,2) NOT NULL,total_amount DECIMAL(12,2) NOT NULL,
 status VARCHAR(20) NOT NULL,created_at DATETIME(3) NOT NULL,expire_time DATETIME(3) NOT NULL,paid_at DATETIME(3),
 UNIQUE KEY uk_user_activity_item(user_id,activity_id,item_id),
 KEY idx_expiry(status,expire_time),FOREIGN KEY(request_id) REFERENCES seckill_request(request_id)
);
CREATE TABLE IF NOT EXISTS payment_record (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,order_id BIGINT NOT NULL UNIQUE,pay_no VARCHAR(100) NOT NULL UNIQUE,
 status VARCHAR(20) NOT NULL,paid_at DATETIME(3) NOT NULL
);
CREATE TABLE IF NOT EXISTS stock_change_log (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,operation_key VARCHAR(150) NOT NULL UNIQUE,request_id VARCHAR(110) NOT NULL,
 item_id BIGINT NOT NULL,order_id BIGINT,change_type VARCHAR(30) NOT NULL,delta INT NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS recovery_outbox (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,operation_key VARCHAR(150) NOT NULL UNIQUE,request_id VARCHAR(110) NOT NULL,
 payload TEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',attempts INT NOT NULL DEFAULT 0,
 next_retry_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),last_error VARCHAR(500),
 KEY idx_outbox_pending(status,next_retry_at)
);
CREATE TABLE IF NOT EXISTS dead_letter_record (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,request_id VARCHAR(110) NOT NULL UNIQUE,payload TEXT NOT NULL,
 reason VARCHAR(500) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'OPEN',attempts INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS experiment (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(160) NOT NULL,architecture_version INT NOT NULL,
 concurrency_count INT NOT NULL,duration_seconds INT NOT NULL,stock INT NOT NULL,notes TEXT NOT NULL,
 results_json LONGTEXT,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
